#ifndef LEXEM_H
#define LEXEM_H
#include "variable.h"

enum LexemType
{
	KEYWORD,
	VARIABLE_DECLARATION,
	FLOW_CONTROL,
	VARIABLE_NAME,
	NUMERIC_CONST,
	OPERATION,
	OPERATOR_DELIMITER,
	PARENTHESES,
	COMMA
};

enum OPERATION_TYPE
{
	UNARY,
	BINARY,
	UNARY_OR_BINARY
};

enum OPERATIONS
{
	ASSIGNMENT = 16666,
	MULTIPLICATION = 15090,
	DIVISION = 10091,
	IS_EQUAL = 10500,
	UNKNOWN_PLUS = 20100,
	BINARY_PLUS = UNKNOWN_PLUS - 5000,
	UNARY_PLUS = UNKNOWN_PLUS - 10000,
	UNKNOWN_MINUS = 20101,
	UNARY_MINUS = UNKNOWN_MINUS - 10000,
	BINARY_MINUS = UNKNOWN_MINUS - 5000,
	UNKNOWN_INCREMENT = 19020,
	POSTFIX_INCREMENT = 10020,
	PREFIX_INCREMENT,
};

enum PARENTHESIS_TYPE
{
	NORMAL_OPEN = 10000,
	NORMAL_CLOSE,
	CURLY_OPEN,
	CURLY_CLOSE,
	SQUARE_OPEN,
	SQUARE_CLOSE,
};

struct Lexem
{
	LexemType type;
	VARIABLE_TYPE var_type;
	OPERATION_TYPE op_type;
	Variable_Record* variable;
	int const_value;
	int code;
	int starting_position;
	int last_position;
	int pair_brace_position;
	int line;

	char* word_string;
};


#endif
